# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME', 'blog.html', 'hackathon.html', '_posts', 'cod.md']

# Site Settings
title: "RZEmiosło.IT | Konferencja programistyczna w Rzeszowie"
email: "kontakt@rzemioslo.it"
description: "Pierwsza konferencja programistyczna w Rzeszowie poświęcona tematyce Software Craftsmanship - dobrym praktykom i metodykom, nie związanymi ściśle z konkretnymi technologiami."
baseurl: "/rzemioslo.it"
url: "http://rzemioslo.it"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-92615330-1"
googleAnalyticsSiteUrl: "auto"
siteVerification: "4-JP2CVATViH_jUFGK_qzECdxzEKOzBRlzlRQMIzQVc"

# Organizer Info
organizerName: ""
organizerAlternateName: ""
organizerDescription: ""
organizerEmail: ""
organizerLogo: ""
organizerLink: ""

# Head
metaKeywords: "RZEmiosloIT, Rzeszów, konferencja, programowanie, software, craftsmanship, IT"
twitterAccount: "@RZEmiosloIT"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook-v3.png"

# Documents
#c4pUrl: ""
#c4sponsorsUrl: ""

# Navigation
navigationLinks:
#- {permalink: "/schedule/", text: "Program"}
- {permalink: "/speakers/", text: "Prelegenci"}
- {permalink: "/team/", text: "Zespół"}
- {permalink: "/logistics/", text: "Logistyka"}
- {link: "http://2017.rzemioslo.it", text: "2017"}
navigationButtons:
 - {permalink: "/#tickets", text: "Kup bilet"}
bottomNavigationLinks:
 - {permalink: "/#tickets", text: "Kup bilet"}
#rightNavigationButtons:
# - {link: "#tickets", text: "Kup bilet"}

# Hero Block
heroImage: "hero.jpg"
#heroButtons:
# - {link: "", text: "Zostań prelegentem"}
# - {permalink: "/#tickets", text: "Kup bilet"}

# About Block
aboutTitle: "O konferencji"
aboutText:
 - "RZEmiosło.IT to pierwsza konferencja programistyczna na Podkarpaciu poświęcona tematyce \"Software Craftsmanship\"."
 - "Nowe technologie pojawiają się i znikają. My wierzymy, że warto inwestować we własne programistyczne rzemiosło, w warsztat, który zawsze będzie aktualny, niezależnie od aktualnych trendów."
 - "Serdecznie zapraszamy!"
#aboutBlock:
# - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
# - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
# - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 10
rockstarSpeakersTitle: "Prelegenci"
rockstarSpeakersButtonText: "Więcej szczegółów"

# Latest News Block
latestNewsTitle: "Aktualności"

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: ""
twitterHashTag: "RZEmiosloIT"
twitterFeed: ""

# Location Block
locationBlockTitle: "Lokalizacja"
eventLocationName: "Podkarpacki Park Naukowo-Technologiczny AEROPOLIS"
eventLocationLink: "http://aeropolis.com.pl/pl/"
eventStreetAddress: "Jasionka 954"
eventAddressLocality: ""
eventAddressLocalityRegion: "Rzeszów"
eventPostalCode: "36-002"
eventAddressCountry: "Polska"
eventStartTime: "2018-05-26T09:00"
eventDoorTime: "08:00"
eventEndTime: "2018-05-26T18:00"
eventPlaceCoordinates: "50.1165296, 22.0175096"
mapCenterCoordinates: "50.082178, 22.003305"
mapMobileCenterCoordinates: "50.082178, 22.003305"

# Venue Block
venueBlockTitle: "Miejsce"
venueBigImage: "venue-0-v2.jpg"
venueSmallImage1: "venue-1-v2.jpg"
venueSmallImage2: "venue-2-v2.jpg"
venueSmallImage3: "venue-3-v2.jpg"
venueTitle: "Podkarpacki Park Naukowo-Technologiczny AEROPOLIS"
venueSubTitle: "Budynek IT"
venueFeatures: ["Nowa sala konferencyjna położona tuż przy lotnisku Jasionka"]

# Partners Block
organizersTitle: "Organizatorzy"
partnersTitle: "Partnerzy"
partnersC4sponsorsButton: "Zostań sponsorem"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Rejestracja rozpoczęta!"
subscribeButtons:
  - {permalink: "/#tickets", text: "Kup bilet"}

# Last edition Block
lastEditionImage: "last-edition.jpg"
lastEditionTitle: "Jak było w 2017 roku?"
lastEditionButtons:
  - {link: "https://www.facebook.com/pg/rzemiosloit/photos/?tab=album&album_id=1783044338622013", text: "Relacja fotograficzna"}
  - {link: "https://www.youtube.com/watch?v=SUaSTnOcod0", text: "Relacja wideo"}
  - {link: "http://2017.rzemioslo.it/media", text: "Media o nas"}

# Tickets Block
ticketsTitle: "Bilety"
ticketsInfo: "Bilety umożliwiają wstęp na wszystkie prezentacje, przerwy kawowe, lunch i afterparty. Nocleg nie jest wliczony w cenę biletu."

# Footer
socialLinks:
#- {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=RZEmiosloIT", icon: "twitter"}
 - {link: "https://facebook.com/rzemiosloit/", icon: "facebook"}
# - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Linki"
  links:
   - {link: "https://www.meetup.com/rg-dev/", text: "rg-dev"}
   - {link: "http://rrug.pl/", text: "rrug"}
 -
  title: "Kontakt"
  links:
   - {link: "mailto:kontakt@rzemioslo.it", text: "kontakt@rzemioslo.it"}
#-
# title: "FAQ"
# links:
#  - {permalink: "", text: "Regulamin"}
#  - {permalink: "", text: "FAQ"}

# Blog
blogTitle: "Aktualności"
blogCommentsEnabled: true
discusShortName: "rzemiosloit"

# Speakers List Block
showSessions: true

# Team Block

# Logistics Find Way Block
findWayTitle: "Wyznacz trasę"
findWayDistance: "Odległość"
findWayDriving: "Samochód"
findWayWalking: "Spacer"
findWayBicycling: "Rower"
findWayTransit: "Transport publiczny"
findWayFindFlight: "Znajdź loty"
logisticsMapCenterCoordinates: "50.082178, 22.003305"
logisticsMapMobileCenterCoordinates: "50.082178, 22.003305"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsWideCards:
#-
# subCards:
#  -
#   title: "Hotele"
#   links:
#    - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel InTourist", address: "ul. Korfantego 45, 35-225 Rzeszów", logoUrl: "hotel_1.gif" }
#    - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel InTourist", address: "ul. Korfantego 45, 35-225 Rzeszów", logoUrl: "hotel_1.gif" }
#  -
#   title: "Restauracje"
#   links:
#    - {link: "https://plus.google.com/b/102444623953913144164", text: "Kura Restaurant", address: "ul. Korfantego 45, 35-225 Rzeszów", logoUrl: "restaurant_1.jpg" }
