# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME', 'blog.html', 'hackathon.html', 'schedule.html', 'team.html', '_posts', 'cod.md']

# Site Settings
title: "RZEmiosło.IT | Konferencja programistyczna w Rzeszowie"
email: "kontakt@rzemioslo.it"
description: "Pierwsza konferencja programistyczna w Rzeszowie poświęcona tematyce Software Craftsmanship - dobrym praktykom i metodykom, nie związanymi ściśle z konkretnymi technologiami."
baseurl: "/rzemioslo.it"
url: "http://rzemioslo.it"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-92615330-1"
googleAnalyticsSiteUrl: "auto"
siteVerification: "4-JP2CVATViH_jUFGK_qzECdxzEKOzBRlzlRQMIzQVc"

# Organizer Info
organizerName: ""
organizerAlternateName: ""
organizerDescription: ""
organizerEmail: ""
organizerLogo: ""
organizerLink: ""

# Head
metaKeywords: "RZEmiosloIT, Rzeszów, konferencja, programowanie, software, craftsmanship, IT"
twitterAccount: "@RZEmiosloIT"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
#c4pUrl: ""
#c4sponsorsUrl: ""

# Navigation
navigationLinks:
# - {permalink: "/schedule/", text: "Rozkład"}
 - {permalink: "/speakers/", text: "Prelegenci"}
# - {permalink: "/team/", text: "Zespół"}
 - {permalink: "/logistics/", text: "Logistyka"}
bottomNavigationLinks:
 - {link: "#tickets", text: "Kup bilet"}
rightNavigationButtons:
 - {link: "#tickets", text: "Kup bilet"}

# Hero Block
heroImage: "hero.jpg"
#heroButtons:
# - {link: "", text: "Zostań prelegentem"}
# - {permalink: "/#tickets", text: "Kup bilet"}

# About Block
aboutTitle: "O konferencji"
aboutText:
 - "RZEmiosło.IT to pierwsza konferencja programistyczna na Podkarpaciu poświęcona tematyce \"Software Craftsmanship\"."
 - "Nowe technologie pojawiają się i znikają. My wierzymy, że warto inwestować we własne programistyczne rzemiosło, w warsztat, który zawsze będzie aktualny, niezależnie od aktualnych trendów."
 - "Serdecznie zapraszamy!"
#aboutBlock:
# - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
# - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
# - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 10
rockstarSpeakersTitle: "Prelegenci"
rockstarSpeakersButtonText: "Więcej szczegółów"

# Latest News Block
latestNewsTitle: "Aktualności"

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: ""
twitterHashTag: "RZEmiosloIT"
twitterFeed: ""

# Location Block
locationBlockTitle: "Lokalizacja"
eventLocationName: "Podkarpacki Park Naukowo-Technologiczny AEROPOLIS"
eventLocationLink: "http://aeropolis.com.pl/pl/"
eventStreetAddress: "Jasionka 954"
eventAddressLocality: ""
eventAddressLocalityRegion: "Rzeszów"
eventPostalCode: "36-002"
eventAddressCountry: "Polska"
eventStartTime: "2017-05-27T09:00"
eventDoorTime: "08:00"
eventEndTime: "2017-05-27T18:00"
eventPlaceCoordinates: "50.1165296, 22.0175096"
mapCenterCoordinates: "50.082178, 22.003305"
mapMobileCenterCoordinates: "50.082178, 22.003305"

# Venue Block
venueBlockTitle: "Miejsce"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Podkarpacki Park Naukowo-Technologiczny AEROPOLIS"
venueFeatures: ["Piękna nowa sala konferencyjna", "Położona tuż przy lotnisku Jasionka"]

# Partners Block
organizersTitle: "Organizatorzy"
partnersTitle: "Partnerzy"
partnersC4sponsorsButton: "Zostań sponsorem"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Zapisz się do newslettera"
subscribeAction: "//twitter.us15.list-manage.com/subscribe/post?u=4ae7f76665dd80a02a0159897&amp;id=75e4a841a1"
subscribeInfo: "Liczba biletów jest ograniczona. Rejestracja rozpocznie się wkrótce..."

# Tickets Block
ticketsTitle: "Bilety"
ticketsInfo: "Bilety umożliwiają wstęp na wszystkie prezentacje, przerwy kawowe, lunch i afterparty. Nocleg nie jest wliczony w cenę biletu."

# Footer
socialLinks:
#- {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=RZEmiosloIT", icon: "twitter"}
 - {link: "https://facebook.com/rzemiosloit/", icon: "facebook"}
# - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Linki"
  links:
   - {link: "https://www.meetup.com/rg-dev/", text: "rg-dev"}
   - {link: "http://www.primebitstudio.com/pl", text: "PrimeBit Studio"}
   - {link: "http://rrug.pl/", text: "rrug"}
 -
  title: "Kontakt"
  links:
   - {link: "mailto:kontakt@rzemioslo.it", text: "kontakt@rzemioslo.it"}
#-
# title: "FAQ"
# links:
#  - {permalink: "", text: "Regulamin"}
#  - {permalink: "", text: "FAQ"}

# Blog
blogTitle: "Aktualności"
blogCommentsEnabled: true
discusShortName: "rzemiosloit"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Wyznacz trasę"
findWayDistance: "Odległość"
findWayDriving: "Samochód"
findWayWalking: "Spacer"
findWayBicycling: "Rower"
findWayTransit: "Transport publiczny"
findWayFindFlight: "Znajdź loty"
logisticsMapCenterCoordinates: "50.082178, 22.003305"
logisticsMapMobileCenterCoordinates: "50.082178, 22.003305"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsWideCards:
#-
# subCards:
#  -
#   title: "Hotele"
#   links:
#    - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel InTourist", address: "ul. Korfantego 45, 35-225 Rzeszów", logoUrl: "hotel_1.gif" }
#    - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel InTourist", address: "ul. Korfantego 45, 35-225 Rzeszów", logoUrl: "hotel_1.gif" }
#  -
#   title: "Restauracje"
#   links:
#    - {link: "https://plus.google.com/b/102444623953913144164", text: "Kura Restaurant", address: "ul. Korfantego 45, 35-225 Rzeszów", logoUrl: "restaurant_1.jpg" }
